name: Build Workflow
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Get Dockerfile
        run: cp ./builds/server_build ./Dockerfile

      - name: Set up QEMU
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract branch name
        shell: bash
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Extract metadata (tags, labels) for Docker
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            yellowbirdconsulting/charles-whitworth
          flavor: |
            latest=true
          tags: |
            type=sha,format=long,prefix=
            type=sha,prefix=${{ steps.extract_branch.outputs.branch }}-,suffix=-{{date 'X'}}
      - name: Build and push
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image digest
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        run: echo ${{ steps.docker_build.outputs.digest }}
